sudo: required
dist: trusty
language: generic
script: make && make test
before_deploy:
- make deploy
deploy:
  provider: releases
  api_key:
  file:
  - dist/password-reverse-proxy.linux.amd64.aci
  - dist/password-reverse-proxy.linux.amd64.aci.asc
  skip_cleanup: true
  on:
    tags: true
    repo: dit4c/password-reverse-proxy
